[project]
name = "liferag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "chromadb>=1.5.5",
    "gradio>=6",
    "langchain>=1.2.13",
    "langchain-chroma>=1.1.0",
    "langchain-core>=1.2.23",
    "langchain-huggingface>=1.2.1",
    "langchain-openai>=1.1.12",
    "psycopg2-binary>=2.9.12",
    "pypdf>=6.9.2",
    "python-dotenv>=1.2.2",
    "sentence-transformers>=5.3.0",
    "sqlalchemy>=2.0.52",
    "streamlit>=1.55.0",
    "onnxruntime==1.24.2",
]
